server:
  port: 8082

# h2 in-memory database: https://www.baeldung.com/spring-boot-h2-database
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: mall1234
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

logging:
  level:
    root: info
    com.macro.mall: debug

host:
  mall:
    admin: http://localhost:8080